# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
## CustomVisionDetails
#  - azureContainerRegistry (ACR Service Connection)
#  - cameracaptureARM (Registry name for Cam Module)
#  - edgedeploymentX64 (Registry name for Edge Deployment API)
#  - imageclassifierARM (Registry name for Image Classifier Model)
#  - sensehatARM (Registry name for Sense Hat Module)
#  - webX64 (Registry name for Web Frontend)
##
- group: CustomVisionDetails

steps:
- template: 'edgedeployment.yml'
- template: 'capturecam.yml'
- template: 'sensehat.yml'
- template: 'imageclassifier-base.yml'
- template: 'imageclassifier-applebanana.yml'
- template: 'imageclassifier-fruits.yml'
- template: 'imageclassifier-fire.yml'
- template: 'imageclassifier-door.yml'
- template: 'imageclassifier-fire_s1.yml'
- template: 'imageclassifier-door_s1.yml'
- template: 'imageclassifier-person.yml'
- template: 'web.yml'







