# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  azureSubscription: 'VSE (FTE) Florian (0c442b21-a8cf-4571-b835-b4d785d6628e)'
  azureContainerRegistry: '{"loginServer":"h2floh.azurecr.io", "id" : "/subscriptions/0c442b21-a8cf-4571-b835-b4d785d6628e/resourceGroups/ContainerRg/providers/Microsoft.ContainerRegistry/registries/h2floh"}'
  imageclassifierARM: 'imageclassifierservice-arm'
  cameracaptureARM: 'cameracapture-arm'
  sensehatARM: 'sensehatdisplay'
  edgedeploymentX64: 'edgedeployment-x64'
  webX64: 'web-x64'
  
steps:
- template: 'edgedeployment.yml'
- template: 'capturecam.yml'
- template: 'sensehat.yml'
- template: 'imageclassifier-base.yml'
- template: 'imageclassifier-applebanana.yml'
- template: 'imageclassifier-fruits.yml'
- template: 'imageclassifier-fire.yml'
- template: 'imageclassifier-door.yml'
- template: 'imageclassifier-fire_s1.yml'
- template: 'imageclassifier-door_s1.yml'
- template: 'imageclassifier-person.yml'
- template: 'web.yml'







