#CaptureCam Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modules/CameraCapture/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CustomVisionDetails

steps:
- template: 'capturecam.yml'