steps:
# Login
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(azureContainerRegistry)

# Edge Deployment x64
- task: Docker@2
  displayName: 'Build and Push Image Edge Deployment x64'
  inputs:
    command: buildAndPush
    Dockerfile: 'modelcontrol/edgedeployment/amd64.Dockerfile'
    repository: '$(edgedeploymentX64)'
    tags: |
      base-$(Build.BuildId)
      latest