#EdgeDeployment Container Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modelcontrol/edgedeployment/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CVSubscriptionDetails
  edgedeploymentX64: 'edgedeployment-x64'

steps:
- template: 'edgedeployment.yml'