#Model Prediction Base Module Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modules/ImageClassifierService/*
    exclude:
    - modules/ImageClassifierService/app/applesbananas/*
    - modules/ImageClassifierService/app/door/*
    - modules/ImageClassifierService/app/fire/*
    - modules/ImageClassifierService/app/fruits/*
    - modules/ImageClassifierService/app/person/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CVSubscriptionDetails
  imageclassifierARM: 'imageclassifierservice-arm'
  cameracaptureARM: 'cameracapture-arm'
  sensehatARM: 'sensehatdisplay'

steps:
- template: 'imageclassifier-base.yml'