#Model AppleBanana Module Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modules/ImageClassifierService/app/applesbananas/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CustomVisionDetails

steps:
- template: 'imageclassifier-applebanana.yml'