#Model Door Module Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modules/ImageClassifierService/app/door/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CustomVisionDetails

steps:
- template: 'imageclassifier-door.yml'