#Model Fire Module Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modules/ImageClassifierService/app/fire_s1/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CVSubscriptionDetails
  imageclassifierARM: 'imageclassifierservice-arm'
  cameracaptureARM: 'cameracapture-arm'
  sensehatARM: 'sensehatdisplay'

steps:
- template: 'imageclassifier-fire_s1.yml'