#Model Fire Module Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modules/ImageClassifierService/app/fire/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CustomVisionDetails

steps:
- template: 'imageclassifier-fire.yml'