#Model Fruits Module Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modules/ImageClassifierService/app/fruits/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CVSubscriptionDetails
  imageclassifierARM: 'imageclassifierservice-arm'
  cameracaptureARM: 'cameracapture-arm'
  sensehatARM: 'sensehatdisplay'

steps:
- template: 'imageclassifier-fruits.yml'