#SenseHat Module Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modules/SenseHatDisplay/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CustomVisionDetails

steps:
- template: 'sensehat.yml'