#Web Container Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modelcontrol/web/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: CVSubscriptionDetails
  webX64: 'web-x64'

steps:
- template: 'web.yml'