#Web Container Only
trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - modelcontrol/web/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  azureSubscription: 'VSE (FTE) Florian (0c442b21-a8cf-4571-b835-b4d785d6628e)'
  azureContainerRegistry: '{"loginServer":"h2floh.azurecr.io", "id" : "/subscriptions/0c442b21-a8cf-4571-b835-b4d785d6628e/resourceGroups/ContainerRg/providers/Microsoft.ContainerRegistry/registries/h2floh"}'
  webX64: 'web-x64'

steps:
- template: 'web.yml'